.travis.yml

Added a travis.yml configuration.

Added a travis.yml configuration.

---

setup.py

add missing pygments dependency

---

.travis.yml
qtconsole/console/ipython_widget.py
qtconsole/console/qtconsoleapp.py
qtconsole/console/rich_ipython_widget.py
qtconsole/inprocess.py
requirements.txt
setup.py

ipython_kernel is now ipykernel

---

examples/jupyter-qtconsole.desktop
qtconsole/qtconsoleapp.py

From the information I've seen, I think this is right, but I can't test it on GNOME 3 for a few more days.
Closes #12
Closes #11

Set application name for Linux desktop frameworks

---

qtconsole/frontend_widget.py

closes #21
backport to IPython 3

handle missing payload

---

qtconsole/console_widget.py
qtconsole/magic_helper.py
qtconsole/mainwindow.py
qtconsole/rich_ipython_widget.py
qtconsole/tests/test_app.py
qtconsole/tests/test_console_widget.py
qtconsole/tests/test_kill_ring.py

- update a few genutils imports
- remove some special treatment of magics

remove some IPython-specific code

---

setup.py

fix path for resources package_data

---

qtconsole/qt.py

Qt5 has better performance, also it’s the currently stable Qt version.
PySide hasn’t had an update in quite some time.

Prefer Qt5

---

qtconsole/frontend_widget.py

Fix copy/paste regressions

---

qtconsole/frontend_widget.py

demote shutdown log to debug

---

docs/autogen_config.py

jupyer typo

---

docs/autogen_config.py
docs/conda-env.yml
docs/source/conf.py
readthedocs.yml

seem to [work](http://carreau-qtconsole.readthedocs.org/en/rtd/) though, there is no toctree.

Build docs on readthedocs.

---

setup.py

resolve https://github.com/jupyter/qtconsole/issues/96 (on windows)

avoid background DOS windows

---

docs/source/index.rst

Writing Qt from within QtConsole is not different from any other REPL.
Saying that the QtConsole is special is even more confusing. which is
paradoxical as this section is trying to explain that QtConsole is not
different.
-- 
Prompted by a personal question I got by mail, in French.

Clarify Documentation.

---

.travis.yml
requirements.txt
setup.py

remove ancient requirements.txt pointing to unreleased packages

update test requirements

---

qtconsole/console_widget.py
qtconsole/qt.py
qtconsole/qt_loaders.py

Added PySide2 support.
The single change in code is `QtGui.qApp` -> `QtGui.QApplication.instance()` (QtGui.qApp was None)

PySide2 support

---

qtconsole/rich_jupyter_widget.py

Closes gh-157
Is this the last bug that has managed to survive since the Python 3 migration? ;-)

Fix JPEG support check in Python 3

---

qtconsole/jupyter_widget.py
qtconsole/pygments_highlighter.py

Change Pygments lexer according to kernel_info

---

setup.py

Add dependency on ipython_genutils

---

qtconsole/console_widget.py
qtconsole/qt_loaders.py
qtconsole/tests/test_completion_widget.py
qtconsole/tests/test_console_widget.py

#164 broke multiline pasting on Linux (and probably Windows). This PR provides a fix.

Fix bug where pasting does not work properly

---

docs/source/changelog.rst

@ccordoba12 Here's an attempt to make the warning less scary for those considering upgrade.

Change warning to a note in changelog

---

docs/source/changelog.rst

This are all the changes I could find since the 4.2.1 release. #199

Adding 4.3 additions to the changelog

---

docs/environment.yml
docs/source/changelog.rst

- Update dependencies for doc build
Example:

Update docs formatting for changelog

---

qtconsole/styles.py

i also deduplicated and DRYed the style templates, and removed the hardcoded border color for dark themes.
in the future maybe we can draw the prompt color from the pygments theme?

Fixed background colors bleeding into borders

---

qtconsole/rich_jupyter_widget.py

Fixes #211.
This pull request fixes issue #211 for me. Tested with example on macOS Sierra 10.12.4 and Python 3.6.1.

Fix TypeError in RichJupyterWidget class

---

qtconsole/console_widget.py
qtconsole/frontend_widget.py

PR: Make %clear to delete previous output on Windows

---

qtconsole/mainwindow.py
qtconsole/qtconsoleapp.py

This is a continuation of the work in #184. Lets you change the color of the current console.
Preview:

PR: Change color scheme of the current console

---

qtconsole/jupyter_widget.py

Clarify help for editor config option

---

qtconsole/rich_jupyter_widget.py

Revert "Add missing newline when printing remote results"

---

qtconsole/frontend_widget.py

PR: Add handling for IndexError when copying the prompt

---

MANIFEST.in

PR: Change MANIFEST.in to reflect renamed LICENSE file

---

docs/source/changelog.rst

@willingc, could you take a look at this one? Thanks!

Update changelog with 4.4 changes

---

qtconsole/rich_jupyter_widget.py

Avoid displaying errors when using Matplotlib to generate pngs from Latex

---

qtconsole/rich_jupyter_widget.py

Fix setting width and height when displaying images

---

CONTRIBUTING.md

Addressing https://github.com/jupyter/qtconsole/issues/302 for beginner friendly contributing page to set up development environments.

Add doc on setting up a dev environment

---

.coveragerc
.travis.yml
qtconsole/console_widget.py
qtconsole/tests/test_console_widget.py

Fix complete statement checks inside indented blocks for Python after IPython 7 release

---

qtconsole/jupyter_widget.py

Part of spyder-ide/spyder#9194

PR: Add language name as attribute of the JupyterWidget

---

setup.py

Also add "Spyder Development Team" as maintainer and update supported Python versions.

Use Readme.md for long_description in setup.py

---

setup.cfg

Remove metadata entry from setup.cfg

---

qtconsole/frontend_widget.py
qtconsole/jupyter_widget.py

PR: Use new traitlets API with decorators

---

README.md

This mostly clarifies pip installation.

Several improvements to the Readme

---

qtconsole/rich_jupyter_widget.py

PR: Inherit widget style in plot's context menu

---

qtconsole/comms.py

PR: Remove __del__ in Comm and fix pep8 warnings

---

qtconsole/pygments_highlighter.py
qtconsole/qstringhelpers.py

Fix emoji highlight

---

qtconsole/completion_widget.py

Fix TypeError in completion widget

---

qtconsole/console_widget.py
qtconsole/frontend_widget.py
qtconsole/tests/test_00_console_widget.py

Fixes #370.
Could that be a new version of qtconsole, so I can use that in https://github.com/spyder-ide/spyder/pull/10087?

Set console to read only after input

---

.travis.yml
qtconsole/call_tip_widget.py
qtconsole/console_widget.py
qtconsole/tests/test_00_console_widget.py

Replace QApp by qApp

---

qtconsole/console_widget.py
qtconsole/rich_jupyter_widget.py

PR: Fix use of QtGui instead of QtWidgets to create QMenu instances

---

.travis.yml
qtconsole/console_widget.py
setup.py

Fixes #415 
Fixes spyder-ide/spyder#11837

PR: Fix some incorrect imports

---

qtconsole/mainwindow.py
qtconsole/rich_text.py

Replace misuses of QtGui

---

.travis.yml
qtconsole/completion_widget.py
qtconsole/tests/test_completion_widget.py

PR: Fix completion widget text for paths and files

---

qtconsole/completion_html.py
qtconsole/console_widget.py

Change font width calculation to use horizontalAdvance

---

docs/gh-pages.py
docs/source/conf.py
qtconsole/completion_html.py
qtconsole/frontend_widget.py
qtconsole/qstringhelpers.py
qtconsole/tests/test_00_console_widget.py
qtconsole/tests/test_comms.py
qtconsole/tests/test_completion_widget.py
setup.py

- remove coding cookies
- remove ``__future__`` import statements
- remove more python 2/3 conditionals
see also #434 for more changes.
Note to reviewer : I am trying to keep the PRs separate to make it easy to review and quick to merge. I apologise if this is adding to noise/notifications.

Remove last bits of python 2 support from package

---

qtconsole/console_widget.py
qtconsole/mainwindow.py

Part of spyder-ide/spyder#12834
Preview:
Pinging @ccordoba12 just in case

PR: Add option to set completion option while running

---

qtconsole/rich_text.py
setup.cfg
setup.py

Remove last bits of Python 2 support

---

setup.py

This error was introduced in PR #452.

Fix error when checking Python version in setup.py

---

qtconsole/pygments_highlighter.py

Qtconsole highlight lines one line at a time so needs to remember state.
Other code may use the lexer; So patch only when relevant.
Closes  #388

Monkeypatch RegexLexer only while in use by qtconsole.

---

qtconsole/console_widget.py

Fixes https://github.com/spyder-ide/spyder/issues/12553

Add Ctrl + Up/Down shortcuts to go to the top/bottom

---

qtconsole/console_widget.py

These implement the keyboard improvements from #483 and #484. 
Fixes #483
Fixes #484

Improve handling of different keyboard combinations

---

qtconsole/manager.py

Fixes https://github.com/jupyter/qtconsole/pull/493/checks?check_run_id=3203252222

KernelManager.post_start_kernel is async in jupyter_client>=7.0

---

qtconsole/call_tip_widget.py

Catch error when trying to delete text_edit widget of CallTipWidget

---

qtconsole/console_widget.py

Fixes spyder-ide/spyder#17153.

Fix another error caused by implicit conversion of float to int

---

qtconsole/console_widget.py

Don't write separator for input prompts

---

.github/workflows/linux-tests.yml
.github/workflows/macos-tests.yml
.github/workflows/windows-tests.yml
qtconsole/console_widget.py
qtconsole/tests/test_00_console_widget.py

See spyder-ide/spyder#17710 for the details.

PR: Fix mixed `input` and `print` statements

---

setup.py

Skip traitlets versions that break Qtconsole on Windows

---

qtconsole/frontend_widget.py

Fixes https://github.com/jupyter/qtconsole/issues/546

Remove non-breaking space in syntax highlighter

---

README.md
docs/source/installation.rst

Update Readme and docs with latest supported Qt versions

---

setup.py

This improves compatibility with the latest releases of PyQt6/PySide6.
Fixes #583.

Require a more recent version of QtPy

---

.github/workflows/linux-tests.yml
.gitignore

Coverage upload step is failing: https://github.com/jupyter/qtconsole/actions/runs/10254373549/job/28536053356?pr=616#step:9:15

Fix workflow coverage upload to coveralls step

---

requirements/environment.yml

Fixes issue described mentioned over https://github.com/spyder-ide/qtconsole/pull/632#issuecomment-2986518442

PR: Fix async kernel test when using conda (CI)
