- jupyter_qtconsole/console/qtconsoleapp.py
Warn about use of deprecated IPythonQtConsole, keeping old config working.
closes #3
> deprecate IPythonQtConsole

- .gitignore
- docs/Makefile
- docs/autogen_config.py
- docs/source/index.rst
Using the newly merged traitlets machinery for this.
@jdfreder when we finalise this, it's probably worth doing something similar for the notebook docs. It looks like in jupyter/notebook#124, you've generated it and committed the output; this approach automatically generates it when building the docs, which should make things easier when we add or change options.
> Document config options for Qt console

- docs/autogen_config.py
- docs/source/conf.py
Including mocking out PyQt4 so it can import the Qt console files.
Ping @jdfreder
> Workaround to generate config docs on RTD

- docs/Makefile
- docs/gh-pages.py
- docs/source/conf.py
My efforts to mock out Qt on Readthedocs didn't work very well, so I think it's simplest to host these docs on gh-pages instead.
This will be at https://jupyter.github.io/qtconsole/dev/
I copied the gh-pages.py script from IPython, updated the repo and changed it to Python 3. I've commented out the command that tries to get the last 3 commits, because there aren't 3 commits yet, so that fails.
> Host built docs on Github pages

- qtconsole/base_frontend_mixin.py
- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/ipython_widget.py
- qtconsole/qtconsoleapp.py
instead of IPython InputSplitter.
Adds a BlockingKernelClient to perform the is_complete_request, since the current use of `_is_complete` can't easily be made async.
based on #19
> use is_complete request to indicate complete input

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- execute on invalid (only 'incomplete' should prevent execute)
- fix shift-enter for forced execution, which was being ignored when `execute_on_complete_input=True`, the default case.
> execute-on-complete fixes

- docs/source/index.rst
Moving information out of the IPython docs. This document seems worth having in order to describe the dependency on PyQt/Pyside, which can't be pip installed.
> Add install docs

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
Mitigate ipython/ipython#8712
Not sure we can make the RichWidget show stars, but we could pop-up a password input.
> Warn qtconsole does not support getpass

- qtconsole/call_tip_widget.py
- qtconsole/completion_widget.py
If there are multiple screens, there completion window and call tips would go out of screen.
> Fix an issue when there are multiple screens

- qtconsole/base_frontend_mixin.py
sibling PRs forthcoming on ipykernel, jupyter_client
needed for in-process kernel
closes #32
> allow kernel client to specify blocking peer class

- qtconsole/qtconsoleapp.py
- qtconsole/tests/test_app.py
the flag was missing from the flags inherited from jupyter_client
jupyter_client fixes the core of the bug in #71, but this should go in anyway.
> fix `juptyer qtconsole --generate-config`

- .travis.yml
Now default Miniconda directory for Python 2 is called `miniconda2` instead of just `miniconda`.
Pinging @minrk about it.
> Fix Travis tests for Python 2

- examples/inprocess_qtconsole.py
This was an example in the old IPython git repo, which was removed when
the code was moved here.  This is mostly just moved, but also changed
the imports to match qtconsole vs IPython.qt.*
> Updated example for creating inprocess qtconsole

- qtconsole/inprocess.py
Fixes #72.
This is needed so that incomplete code typed into the console triggers multiline editing when using an in-process kernel.
> Provide an in-process version of RichJupyterWidget

- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installation.rst
Addresses #82 for Sphinx docs.
> Update index of Sphinx docs

- qtconsole/rich_jupyter_widget.py
Currently it just prints an error and gives an empty png. However, there is a
lot of LaTeX that matplotlib cannot parse, e.g., matrices. This gives a better
user experience for SymPy, which has a text printer that it can fallback
to. SymPy cannot just disable the LaTeX printer because it is desired for the
notebook, and there is no way for it to enable LaTeX just in the notebook, or
change the printer precedence order.
I have left in the debug logging of the error (to the terminal).
Fixes #63. This supersedes #57, although I don't know if it fixes the issue
there.
> Fallback to the string printer if the latex printer raises an exception

- qtconsole/qt_loaders.py
> If a Qt binding is already loaded, use it.

- qtconsole/completion_html.py
- qtconsole/console_widget.py
Previously the calculation for how to lay out the tab-completion suggestions just assumed a display width of 80 characters. This fixes it to use the correct width.
Fixes #84.
> Fix number of columns for ncurses tab completion

- qtconsole/rich_jupyter_widget.py
Fixes #56 
This builds on top of ipython/ipython#9203, so that one has to be merged first.
Pinging @flying-sheep, @asmeurer and @jorisvandenbossche
----
Tasks:
> Fix Latex support

- qtconsole/completion_widget.py
- qtconsole/tests/test_completion_widget.py
Currently, if you click on the `CompletionWidget` with the mouse, it gets focus (Windows 10, 64-bit, PyQt4). This triggers the `CompletionWidget` to hide. To prevent this, check the active window before hiding. Next, since it now has focus, any keyboard input to the `CompletionWidget` needs to be redirected to its `_text_editor`, except the input that is intended for it (up/down/page up/page down/home/end).
> Fix droplist completer focus

- qtconsole/jupyter_widget.py
- qtconsole/mainwindow.py
- qtconsole/usage.py
Fixes #78 
----
I'll create a corresponding pull request in the IPython repo to remove `gui_reference` from it.
> Remove %guiref and add instead an entry in our Help menu to show its contents

- qtconsole/console_widget.py
When pressing the "Backtab" key the current line will be moved to
the left so that the first non whitespace character has a position
which is a multiple of 4 (since tab = 4 spaces).
> Backtab key event added

- qtconsole/console_widget.py
Changed to fit the tab raster. Instead of always inserting 4
spaces, tab will now insert 1 to 4 spaces so that the cursor end up
on a multiple of four spaces.
> Tab key event updated

- qtconsole/console_widget.py
The Enter/Return key event is updated to also indent new lines
within an existing text block. Currently only lines added at the
bottom of the console are indented.
> Enter, Return key event modified

- qtconsole/console_widget.py
- qtconsole/util.py
And apply it to QWidget in ConsoleWidget.
Fixes double-initialization in ConsoleWidget with:
- PySide
- traitlets 4.2, which calls super in `__init__` now
closes #104
> Make SuperQObject logic reusable with other Qt bases

- qtconsole/console_widget.py
Move cursor to beginning of text instead of beginning of line
in the case line starts with leading spaces. This is the same
behaviour used by common text editors/IDEs like SublimeText
and PyCharm.
> Home key event updated.

- qtconsole/jupyter_widget.py
fixes regression where prompt would never be shown for `--existing`
consoles.
closes #115
> request kernel_info on start_channels

- docs/source/changelog.rst
- qtconsole/console_widget.py
- qtconsole/tests/test_console_widget.py
Fixes #124
Not sure what should be done with the changelog to document this.
> BUG: Rename width/height traits to avoid QWidget override.

- docs/autogen_config.py
Based on feedback in another repo https://github.com/jupyter/help/issues/13#issuecomment-206039381, this PR adds documentation about ``jupyter qtconsole --help-all``.
> Add --help-all doc

- qtconsole/qt_loaders.py
**Exception:**
```
> python.exe -m qtconsole
Traceback (most recent call last):
File "C:\Python\3.5\Win64\lib\runpy.py", line 184, in _run_module_as_main
"__main__", mod_spec)
File "C:\Python\3.5\Win64\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Python\3.5\Win64\lib\site-packages\qtconsole\__main__.py", line 2, in
<module>
from qtconsole.qtconsoleapp import main
File "C:\Python\3.5\Win64\lib\site-packages\qtconsole\qtconsoleapp.py", line 6
0, in <module>
from qtconsole.qt import QtCore, QtGui
File "C:\Python\3.5\Win64\lib\site-packages\qtconsole\qt.py", line 23, in <mod
ule>
QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
File "C:\Python\3.5\Win64\lib\site-packages\qtconsole\qt_loaders.py", line 314
, in load_qt
if not can_import(api):
File …
```
> qt_loaders: bugfix for imp.find_module failure on Python 3.5 Windows 7

- README.md
- docs/source/installation.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- qtconsole/mainwindow.py
Added the shortcut <kbd>Ctrl+R</kbd> to rename the current tab.
It also appears in the `Window` menu.
Closes #122. Relevant to #100 as well.
> Added a keyboard shortcut for renaming the current tab.

- qtconsole/ansi_code_processor.py
- qtconsole/tests/test_ansi_code_processor.py
Support 24bit True Color ansi code sequences [1].
This PR will make more command lines output usable and will support the output of some Python libraries including Pygments's TerminalTrueColorFormatter output.
[1] https://gist.github.com/XVilka/8346728
> Add ansi 24bit true color support

- qtconsole/mainwindow.py
The <kbd>Alt+R</kbd> hotkey now renames the main QtConsole window.
This closes #100 .
> Added hotkey to rename the QtConsole window.

- qtconsole/frontend_widget.py
- qtconsole/jupyter_widget.py
IPython kernels no longer set the status='error' flag when executing a script using %run. Instead, a new message type 'error' is used for passing error messages around.
This PR adds a hacky fix to demonstrate the problem. Someone with a better grasp of the codebase than me should take a look and implement a clean solution.
fixes #156, #140
> [MRG] Fix error messages when using %run

- qtconsole/mainwindow.py
- qtconsole/qtconsoleapp.py
Fixes #101 
The code does what is should, but I have 2 issues that need to be addressed:
1. Choosing the kernel. Currently you just enter the kernel name (from the `--existing` option). We might want something more user friendly,
2. Naming the new tab - should it be automatic ("external 0", "external 1" and so on) or user defined?
> Create new tab with existing kernel

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/jupyter_widget.py
- qtconsole/tests/test_console_widget.py
Since the `QTextEdit` object that we use as main text widget has the `maximumBlockCount` constraint set, lines of text can get removed from the beginning of the document at any time text is append to the document.
This PR fixes a particularly nasty bug where `self._append_before_prompt_pos` is incorrectly computed, leading to the `QTextCursor::setPosition: Position '14083' out of range` error.
It is important to keep proper track of the beginning and end position of the prompt, also when text is inserted or removed. Instead of manually tracking this position by computing offsets when doing text operations, this PR uses QTextCursor objects to do this.
Fixes #76, #94, #107
> [MRG] Fix "invalid cursor position" error

- qtconsole/qt_loaders.py
Closes gh-160
Tested manually with PyQt5. I haven't tried with PySide2, I just copied the code.
> Add QtPrintSupport to QtGui compatibility bucket

- qtconsole/mainwindow.py
For some reason CMD+SHIFT+LEFT/RIGHT doesn't activate the proper menu item. Perhaps OSX captures this shortcut somewhere. This PR remaps the tab switching shortcuts on OSX to CMD+ALT+LEFT/RIGHT.
Closes #155.
> Change tab switch shortcut to CMD+ALT+LEFT/RIGHT on OSX

- qtconsole/console_widget.py
- qtconsole/history_console_widget.py
Fixes https://github.com/spyder-ide/spyder/issues/3215
> Make browse history to work for lines longer than the console's width

- qtconsole/console_widget.py
On OSX, Ctrl+K is mapped to 'cut', Ctrl+Y is mapped to 'paste', etc. These interfere with the readline-like binding we'd like to support on this platform (e.g. Ctrl+K should delete everything until the end of line). This PR shuffles the priority of the keyboard shortcuts, so that the readline-like bindings get priority.
> Stop special sequences from overriding custom keyboard shortcuts

- qtconsole/qt_loaders.py
This provides a new implementation for Python >= 3.4, leaving the existing one for Python <= 3.3.
Closes gh-168 (hopefully; I can't reproduce it to test)
> Fix PyQt import checks on Python 3.5

- qtconsole/rich_jupyter_widget.py
When using python 3, saving to HTML with inline PNG images is reported broken (#51). This fixes it.
fixes #51
> Fix saving HTML with inline PNG for python3

- qtconsole/ansi_code_processor.py
- qtconsole/jupyter_widget.py
- qtconsole/tests/test_jupyter_widget.py
- qtconsole/tests/test_styles.py
When working with a light background, QtConsole changes the internal ansi color table to disable light variants of the colors, which would be unreadable. This fixes a bug where a light background would always be detected, even when a dark style was selected.
fixes #49
> [MRG+1] Fix ansi color table when changing syntax styles

- qtconsole/mainwindow.py
The previously linked page has a warning that it is obsolete and points to http://ipython.readthedocs.io/en/stable/
> [MRG+1] Update URL to ipython documentation

- qtconsole/console_widget.py
If I run the following example, which has no banner:
```python
from qtconsole.inprocess import QtInProcessKernelManager
from qtconsole.rich_jupyter_widget import RichJupyterWidget
if __name__ == "__main__":
from qtpy.QtWidgets import QApplication
app = QApplication([''])
kernel_manager = QtInProcessKernelManager()
kernel_manager.start_kernel()
kernel_client = kernel_manager.client()
kernel_client.start_channels()
widget = RichJupyterWidget()
widget._display_banner = False
widget.kernel_manager = kernel_manager
widget.kernel_client = kernel_client
widget.shell = kernel_manager.kernel.shell
widget.show()
app.exec_()
```
I get the following errors:
```
QTextCursor::setPosition: Position '-1' out of range
QTextCursor::setPosition: Position '10' out of range
```
This is because in the attached …
> Don't move cursor back then forward if there is no banner

- qtconsole/svg.py
I do not know if QImage used to automatically clear the internal buffer in the past, but it does not do so on my machine  (Fedora 25, Qt 5.7.1). Therefore SVG rendering is broken for me, because the internal QImage bufer is never cleared before being rendered upon.
This leads to all sorts of rendering artefacts  as to be expected when rendering uninitialized data. A particularly annoying case is when the allocator gives the same memory chunk to QImage for different images with transparency. The result is, as you might expect, all the images consecutively rendered into the same buffer.
I tracked the bug to `svg_to_image()` in `qtconsole/svg.py
`
The fix is very trivial, just add a line with image.fill(0) before initializing the painter.
> Initialize QImage before rendering SVG

- qtconsole/console_widget.py
This PR restores moving the cursor back one place before inserting the prompt, for situations where there _is_ already some content in the console. This fixes a regression that I believe was accidentally introduced in #224.
Post #224, I see extra console messages in my qtconsole-using application that weren't present in the 4.3.0 release:
```
QTextCursor::setPosition: Position '428' out of range
```
I also see an extra test failure that wasn't there before (the second failure below; the first is already present with the 4.3.0 release on my machine):
```
(qtconsole-testing)bash-3.2$ nosetests qtconsole/
................QTextCursor::setPosition: Position '15' out of range
F.QTextCursor::setPosition: Position '53' out of range
F........ …
```
> Restore cursor position move before inserting prompt

- qtconsole/base_frontend_mixin.py
- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/history_console_widget.py
- qtconsole/tests/test_console_widget.py
As elaborated in #174, qtconsole blocks the event loop trying to figure out whether a command is complete. This PR fixes that: it introduces a complete callback mechanism instead. When we want to know whether a command is complete, we send it to the kernel, and register a callback for the response.
If the kernel does not respond until the user wants to continue editing, we simply assume that the code was not complete.
This PR also removes the code for creating a blocking client, as this is not needed anymore.
Closes #174
> Do not block event loop

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/jupyter_widget.py
- qtconsole/tests/test_frontend_widget.py
- qtconsole/tests/test_jupyter_widget.py
The `c.ConsoleWidget.include_other_output = True` switch will make QtConsole display input given to the kernel that was initiated by other clients. For example, a text editor can connect to the kernel and allow users to select pieces of code and execute them (like the F9 button in Spyder and MATLAB).
This PR fixes some bugs and adds some enhancements when displaying "other_input" and "other_output".
1. Adds an `[remote] In [n]: ` prompt for other_input and an `[remote] Out[n]: ` prompt for other_output (like jupyter-console does)
2. Adds a configuration option `other_output_prefix` to change the `[remote] ` prefix above to something else (like jupyter-console has)
3. Fixes the syntax highlighting of other_input. The decision on whether to highlight a block is made based on whether the …
> Enhance handling of input from other clients

- qtconsole/console_widget.py
- qtconsole/tests/test_console_widget.py
This stops them from deleting too greedily across line boundaries.
> foo = ['foo', 'foo', 'foo',
>       'bar']
One Ctrl+Backspace will do:
> foo = ['foo', 'foo', 'foo',
>       '
Another will do:
> foo = ['foo', 'foo', 'foo',
>
And another will do:
> foo = ['foo', 'foo', 'foo',
Also PEP8-i-fied some related code.
Fixes #241
> Make behavior of Ctrl+Backspace and Ctrl+Delete more intelligent

- docs/source/index.rst
- examples/embed_qtconsole.py
- examples/inprocess_qtconsole.py
Starting the kernel in a separate process should be the default option for most users.
Closes gh-243
> Create a simple example of embedding, and clarify docs.

- qtconsole/console_widget.py
- qtconsole/tests/test_console_widget.py
Starting with the following snippet
```
If True:       
if False:        # line A
pass  # line B
```
If I copy Block AB, selecting two complete lines, with indentation, and paste it into qtconsole in an indented position:
```
While Foo:
_ # cursor here, <paste>
```
The result is:
```
While Foo:
if False:        # line A
pass  # line B
```
When I'd expect to see:
```
While Foo:
if False:        # line A
pass  # line B
```
> Fix paste dedent corner case

- qtconsole/base_frontend_mixin.py
- qtconsole/completion_html.py
- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/history_console_widget.py
- qtconsole/jupyter_widget.py
- qtconsole/mainwindow.py
- qtconsole/qtconsoleapp.py
- qtconsole/svg.py
- qtconsole/tests/test_kill_ring.py
Get rid of all training whitespace. This gets placed by accident. Let's clean it up!
Ran the following on the source code:
python -m autopep8 --select W2 -i qtconsole/*.py
python -m autopep8 --select W2 -i qtconsole/tests/*.py
> Eliminate training whitespace

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/tests/test_console_widget.py
Here's the first cut for #249. Before merging I'd like to use it for a week or so to flush out any kinks I may have introduced, but code review and testing by other interested folks is welcome.
Intention is to:
- Preserve current indent behavior when no selection is active.
- If selection **is** active, de/indent whole block by same amount, as determined by the column of the first line in the selection (indent is still done to next 4-space boundary).
Please advise on use of existing `self._tab_width=8` vs. (the new) `self._indent_width=4`.
Also noticed the criteria for triggering completion is puzzling: https://github.com/jupyter/qtconsole/blob/8508ce1e815867743dd4bb84534ebe4cfebbdc11/qtconsole/frontend_widget.py#L279
That's *"before"* and not *"right before"* , which means that:
```
In …
```
> Implement Block de/indent 

- qtconsole/console_widget.py
- qtconsole/mainwindow.py
- qtconsole/tests/test_console_widget.py
closes #257
Hit once: select current cell
Hit again: select whole document
Hit yet again: select cell again
@ccordoba12 @takluyver @wmvanvliet
> Change Ctrl-S-A to to select cell first, then whole document

- qtconsole/console_widget.py
- qtconsole/tests/test_console_widget.py
Currently, pressing the right arrow key when at the end of a line always moves the cursor to the end of the cell, even when the cell has multiple lines. The intended behaviour was to move the cursor to the next line (respecting the continuation prompt). See #245 for more details.
Fixes #245
> Fix behaviour of right arrow key

- qtconsole/rich_jupyter_widget.py
When qtconsole is mirroring another session, (e.g. `jupyter qtconsole --existing --JupyterWidget.include_other_output = True`) the output messages from the other session get printed on the same line as the input. This commit fixes that.
> Add missing newline when printing remote results

- qtconsole/qt_loaders.py
This fixes a bug in commit_api which caused PySide2 binding to be forbidden even if the loaded API was PySide2 (I think it was just a typo in the if statement)
> Fix compatibility with PySide2 on Python 2.7

- qtconsole/frontend_widget.py
I noticed that I occasionally get an `AttributeError` while using qtconsole:
```
Traceback (most recent call last):
File "/build/Python/linux-x86_64/lib/python3.6/site-packages/qtconsole/frontend_widget.py", line 70, in highlightBlock
if not self.highlighting_on:
AttributeError: 'FrontendHighlighter' object has no attribute 'highlighting_on'
```
I am guessing that this happens because some object which was not created by `FrontendHighlighter.__init__()` ends up calling FrontendHighlighter.highlightBlock(), but the `highlighting_on` attribute does not actually exist on that object. This PR should fix the problem.
> Check that the highlighting_on attribute exists before accessing it

- qtconsole/console_widget.py
- scripts/jupyter-qtconsole
Fixes #289 
This code enters an EOT character when ctrl-d is pressed if kernel is executing and input buffer is empty. This preserves ctrl-d as a delete shortcut and a close tab shortcut.
> [PR] Make Ctrl-D enter an EOT character if kernel is executing and input is empty

- README.md
Instead of having debian package installation instructions (which are already available in the qtconsole docs), the PyQT docs have been linked for alternative ways to install pyqt. Links to both pyqt4 and pyqt5 source packages for Windows/MacOS/Linux have been added.
> Update installation instructions for pyqt

- qtconsole/qt_loaders.py
Fixes #291 
According to the [list of PyQt incompatibilities](http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html#pyqt-v5-11) moving the `import sip` statement is sufficient (I think).
> Fix PyQt5 sip module incompatibility

- qtconsole/frontend_widget.py
- qtconsole/ipython_widget.py
- qtconsole/jupyter_widget.py
- qtconsole/qtconsoleapp.py
- qtconsole/rich_ipython_widget.py
- qtconsole/rich_jupyter_widget.py
This PR was prompted by a flood of identical warnings found as part of spyder/spyder-ide#8173 and described in spyder/spyder-ide#8174 that originated due to QtConsole needing to be passed ``local_kernel`` when creating new ``FrontEndWidgets``, but that then being passed on to ``traitlets`` as unrecognized arguments which are deprecated and will soon raise an error. Therefore, @ccordoba12 requested I implement the fix I suggested here, and to my pleasant surprise everything worked; all the Spyder tests (including the ``--run-slow`` ones) passed and no DeprecationWarnings were raised.
Aside from fixing that issue, it fixes a few other DeprecationWarnings found via the Spyder test suite (I couldn't run QtConsole's own ``nose`` tests locally due to it generating a ``..........Fatal Python …
> Cleanup deprecation warnings from to other packages and make QtConsole's own proper DeprecationWarnings

- .gitignore
- .travis.yml
- CONTRIBUTING.md
- qtconsole/console_widget.py
- qtconsole/tests/__init__.py
- qtconsole/tests/test_app.py
- qtconsole/tests/test_completion_widget.py
- qtconsole/tests/test_console_widget.py
- qtconsole/tests/test_frontend_widget.py
- qtconsole/tests/test_jupyter_widget.py
- qtconsole/tests/test_kill_ring.py
- qtconsole/tests/test_styles.py
- setup.py
This is because nose is not maintained anymore.
> PR: Move testing infrastructure to use pytest

- qtconsole/console_widget.py
- qtconsole/tests/test_console_widget.py
Stop the cursor from moving at the end while debugging.
Fixes #330.
> Fix cursor not moving while debugging

- qtconsole/comms.py
- qtconsole/kernel_mixins.py
- qtconsole/tests/test_comms.py
Add comms to qtconsole.
This is based on:
https://jupyter-notebook.readthedocs.io/en/stable/comms.html
https://jupyter-client.readthedocs.io/en/latest/messaging.html
The code is adapted from:
https://github.com/jupyter/notebook/blob/master/notebook/static/services/kernels/comm.js
https://github.com/ipython/ipykernel/blob/master/ipykernel/comm/manager.py
https://github.com/ipython/ipykernel/blob/master/ipykernel/comm/comm.py
> PR: Add Comms to qtconsole

- setup.py
This is a requirement to be able to use markdown in the `long_description` field. Due to this tarballs couldn't be uploaded to PyPI for 4.5.0.
> Move setup.py to use setuptools instead of distutils

- qtconsole/console_widget.py
Fixes #347 
Explanation
Qtconsole treats commands from an external frontend (remote) differently than commands done locally. However all remote commands go through the function "_append_custom" where I added the line to scroll to the end of the console.
> Scroll down for output from remote command

- qtconsole/completion_html.py
- qtconsole/completion_plain.py
- qtconsole/completion_widget.py
- qtconsole/console_widget.py
> PR: Inherit console widget style and handle cursor position in the completion widget

- qtconsole/console_widget.py
- qtconsole/manager.py
Removed some of the deprecation warnings (implicit casting to int). This gets rid of the almost 4000 warnings in Spyder related to qtconsole. 
A few more than those explicitly pointed out in the Spyder logs are fixed, but I cannot say that these are all.
> Remove deprecation warnings in Python 3.8

- .travis.yml
- qtconsole/console_widget.py
- qtconsole/tests/test_00_console_widget.py
- qtconsole/tests/test_a_console_widget.py
> PR: Fix scrolling issues

- qtconsole/console_widget.py
If text is added to the console, even if the console is not executing, the console should scroll.
> Scroll when adding text even when not executing.

- qtconsole/frontend_widget.py
- qtconsole/jupyter_widget.py
Autocomplete will fail it text is added to the console between the autocomplete request and the autocomplet reply, even if this text is added before the prompt. I would expect this to fail only if the prompt is changed. Therefore, instead of checking the absolute position, this checks the prompt buffer and the position in the prompt buffer.
> Allow text to be added before the prompt while autocompleting

- qtconsole/console_widget.py
Added the visibility of the side scrollbar as a configurability option.
> Add an option to configure scrollbar visibility

- qtconsole/console_widget.py
- qtconsole/tests/test_00_console_widget.py
Wait 250ms for a reply from is_complete instead of giving up immediately.
fix #372
> Wait for a reply from is_complete instead of giving up immediately

- qtconsole/comms.py
When closing, the comms might send closing messages back and forth. Therefore, ignore closing messages for closed comms as this is expected.
> Ignore missing comms while closing

- qtconsole/completion_widget.py
- qtconsole/tests/test_00_console_widget.py
- qtconsole/tests/test_comms.py
A preview:
Fixes spyder-ide/spyder#10692
Pinging @ccordoba12 just in case
> Prevent completion strip if it refers to a file

- qtconsole/history_console_widget.py
> Skip history if it is the same as the input buffer

- qtconsole/frontend_widget.py
- qtconsole/mainwindow.py
@ccordoba12 a preview:
Fixes #396
> Remove code to expand tabs to spaces

- qtconsole/svg.py
This was detected by the Spyder test suite.
> Add missing import to svg module

- qtconsole/jupyter_widget.py
`self._previous_prompt_obj` stores information about the current prompt's length. JupyterWidget's `self._show_interpreter_prompt` sets `self._previous_prompt_obj`. A call to `self._update_prompt` only updates the displayed text, not also updating `self._previous_prompt_obj`. 
This isn't an issue when all prompts are the same length, which is the case in IPython. But if you use prompts of different length, the next `Out []` line is shown on the same line, covered by the prompt. It's also moved to the right by an amount dependent on the length of the input.
Why prompts of different length? I'm subclassing the class in a rewrite of Orange's Python Script widget https://github.com/biolab/orange3/pull/4402, where I call these private methods to show that a script (written in a separate code …
> Set updated prompt as previous prompt object in JupyterWidget

- .travis.yml
@ccordoba12 ~~at the end I removed the testing in Python 2.7 (no idea what is causing the memory segfault, the only difference I saw in the logs was the change from Python `2.7.17` to Python `2.7.18` and that the Qt version changed from `5.9.7` to `5.9.4`)~~ seems like using Python 2.7.17 prevents the tests segfault in Python 2
> PR: Fix Python 2 tests

- qtconsole/call_tip_widget.py
This is a fix for jupyter/qtconsole#383. It applies the same modification to the `CallTipWidget` `hideEvent` function as that used to fix `CompletionWidget` in #367. 
Fixes #383.
> Fix a TypeError in CallTipWidget

- qtconsole/qtconsoleapp.py
As described in #405, the qtconsole is currently not working on windows. As a workaround, this PR sets the default asyncio policy on windows with python 3.8 when the app object is created.
For more details, see https://github.com/ipython/ipykernel/pull/480 and https://github.com/tornadoweb/tornado/issues/2608.
Fixes #405.
> Make Qtconsole work on Python 3.8 and Windows

- qtconsole/console_widget.py
Verify if the event has button as an attribute before calling `event.button()`
Fixes https://github.com/spyder-ide/spyder/issues/12524
> PR: Verify if event has attribute button

- .travis.yml
- qtconsole/jupyter_widget.py
If an execution request is sent before the prompt is shown, the input is not shown. This solves this problem. CF: https://github.com/spyder-ide/spyder/issues/13048
> Print input if there is no prompt

- qtconsole/call_tip_widget.py
- qtconsole/console_widget.py
In newer versions of __PySide2__ the attribute _qApp_ of module _QtWidgets_ is removed.
This PR changes all the occurrences of _qApp_ with _QApplication.instance()_
As this attribute doesn't exist on newer versions of PySide2 it causes a crash on my application.
This doesn't affect previous versions of PySide2 as _qApp_ attribute is the same as _QApplication.instance()_, verified on PySide2 5.11.2.
Tested on __PySide2 5.15.0 LTS__.
> Replace qApp with QApplication.instance()

- qtconsole/bracket_matcher.py
- qtconsole/call_tip_widget.py
- qtconsole/comms.py
- qtconsole/completion_html.py
- qtconsole/completion_plain.py
- qtconsole/completion_widget.py
- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/history_console_widget.py
- qtconsole/inprocess.py
- qtconsole/jupyter_widget.py
- qtconsole/kernel_mixins.py
- qtconsole/kill_ring.py
- qtconsole/mainwindow.py
- qtconsole/manager.py
- qtconsole/pygments_highlighter.py
- qtconsole/qtconsoleapp.py
- qtconsole/rich_jupyter_widget.py
This PR updates the use of `super` i.e. it replaces `super(ClassName, self).` with `super()` which is the recommended way on Python 3.
> Use new Python 3 super syntax

- docs/source/conf.py
- qtconsole/completion_html.py
- qtconsole/console_widget.py
- qtconsole/jupyter_widget.py
- qtconsole/pygments_highlighter.py
- qtconsole/qtconsoleapp.py
- qtconsole/rich_text.py
- qtconsole/tests/test_00_console_widget.py
- qtconsole/tests/test_jupyter_widget.py
The u-string prefixes are redundant and unnecessary on python 3. Note that this was split into a standalone PR given the volume of changes.
> Remove u-string prefixes

- qtconsole/manager.py
`kernel_restarted` is emitted just before restarting the kernel, which doesn't really make sense. This emits it just after restarting the kernel.
> Emit kernel_restarted after restarting kernel

- setup.py
This change adds a python_requires directive, which prevents installing on unsupported Python versions. This is intended to fix #455 (And its duplicate #456), once a new release has been cut, and the bad release pulled.
Fixes #455.
> Add python_requires for Python 3.6+ compatibility

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/tests/test_jupyter_widget.py
When copying, qtconsole removes whole prompts, but not partial prompts. This removes partial prompts on the first line.
> PR: Remove partial prompt on copy

- qtconsole/frontend_widget.py
Edge case forgotten in https://github.com/jupyter/qtconsole/pull/462
When the last selected line is the last line of the console, contains a prompt, and only partially selects the prompt
> PR: Fix edge case copy last line

- qtconsole/qtconsoleapp.py
Similar fixes as in https://github.com/spyder-ide/spyder/pull/14256. 
Relevant links:
https://bugreports.qt.io/browse/QTBUG-87014
https://github.com/matplotlib/matplotlib/issues/18954
It is fixed in qt 5.15.2 (https://codereview.qt-project.org/c/qt/qtbase/+/322228) and in the coming 5.12.11 (https://codereview.qt-project.org/c/qt/qtbase/+/322507) and confirmed in https://stackoverflow.com/questions/64818879/is-there-any-solution-regarding-to-pyqt-library-doesnt-work-in-mac-os-big-sur/64856281 that setting this environment variable is not necessary for qt >=5.15.2.
> Fix launching issue with Big Sur

- qtconsole/manager.py
`kernel_restarted` should only be emitted when the kernel dies and restart, but is now emitted on any restart following #450. This solves this issue, and fixes https://github.com/spyder-ide/spyder/issues/14886
> Emit kernel_restarted only after crashing

- qtconsole/tests/test_comms.py
This change is needed for the next release of jupyter_client, and has no impact on the current code base anyway.
See #477
> Change Empty import

- qtconsole/console_widget.py
Move cursor to beginning of buffer if on the same line.
Now when pressing 'b' from
`In [2]:| aaa`
leads to:
`In [2]: aaab`
After this PR:
`In [2]: baaa`
> Move cursor to beginning of buffer if on the same line

- qtconsole/call_tip_widget.py
The CallTipWidget acts like a tooltip and has no parent. As such,
it would be leaked without this explicit lifetime management.
> Destroy CallTipWidget when corresponding TextEdit is destroyed

- qtconsole/ansi_code_processor.py
Replace \, by \\, which is how python currently interprets it.
r"" would be incorrect as the \x1b would be escaped.
Checked that ANSI_PATTERN is unchanged to:
In [7]: ANSI_PATTERN
Out[7]: '\x01?\x1b(\\[(.*?)([ABCDEFGHJKSTfmnsu])|\\](.*?)[\x07\x1b])\x02?'
> Fix DeprecationWarning: invalid escape sequence.

- qtconsole/base_frontend_mixin.py
- qtconsole/frontend_widget.py
- qtconsole/jupyter_widget.py
The requests are not necessarily sent after receiving the reply from the previous request. If several request are sent in rapid succession, `self._hidden` becomes meaningless. The hidden state of each request must therefore be saved.
Also, the prompt was sometimes requested several times, so to avoid multiple confusing prompt, a check is added.
> Fix hidden execution requests

- qtconsole/ansi_code_processor.py
- qtconsole/console_widget.py
- qtconsole/tests/test_00_console_widget.py
- qtconsole/tests/test_ansi_code_processor.py
It is related to #350.
It now fixes the K ANSI code (Erase in Line) supporting:
-  0K for 'until end', 
- 1K for 'until start', 
- 2K for all line (whole). 
1/ I hope my code does not break anything; it can, as I had to change '\r' carriage return & '\b' that strangely used to keep the cursor in position.  Somehow I have implemented a more natural 'replace text' mode (instead than default insert mode).
2/ There was a misunderstanding of the specs requiring not to move the cursor ([ANSI code](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences)).
Therefore I had also to replace sometimes the removed text by spaces.
I guess it is WIP.
Some examples, giving similar results in Python & IPython, AFAI've checked.
```
print('Hello\x1b[1KBye')    # " …
```
> Fix ANSI code "Erase in Line"

- qtconsole/console_widget.py
There was an issue when pressing left key before newline, eg:
`In [1]: print('foo')`
would have printed
`In[1]: print('foo')foo`
However the CI tests were successful and I did not add a new one for this case (my apologize).
> Fix 'Erase in Line' ANSI code

- qtconsole/call_tip_widget.py
* Subclasses the CallTipWidget `deleteLater` function to catch errors caused by the prior deletion of the underlying C/C++ widget.
* Supersedes the exception handling in the CallTipWidget `__init__` function.
* Simplifies the specification of the slot connected to the `destroyed` signal.
* Fixes #507.
> Fix error when deleting CallTipWidget

- docs/environment.yml
The build is broken because we were using an old Python version.
> Try to fix building docs

- qtconsole/completion_widget.py
Implicit conversion to integers using __int__ was deprecated, and now removed in Python 3.10.
Running tests in 3.9:
```
qtconsole/tests/test_completion_widget.py::TestCompletionWidget::test_common_path_complete
qtconsole/tests/test_completion_widget.py::TestCompletionWidget::test_droplist_completer_keyboard
qtconsole/tests/test_completion_widget.py::TestCompletionWidget::test_droplist_completer_keyboard
qtconsole/tests/test_completion_widget.py::TestCompletionWidget::test_droplist_completer_mousepick
qtconsole/tests/test_completion_widget.py::TestCompletionWidget::test_droplist_completer_mousepick
qtconsole/tests/test_completion_widget.py::TestCompletionWidget::test_droplist_completer_shows
/build/python-qtconsole/src/qtconsole-5.2.1/qtconsole/completion_widget.py:171: DeprecationWarning: …
```
> Fix implicit int to float conversion

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- setup.py
> Drop support for Python 3.6 because it reached end-of-life

- qtconsole/rich_jupyter_widget.py
Since [7.8.0](https://github.com/ipython/ipython/pull/11840), `IPython's latextool.latex_to_png()` has a `color` keyword for setting the foreground color. Let's use it.
This resolves style problems for any `_latex_repr_()` rendering which does not come from SymPy, e.g. Astropy or python-control.
```python
In [1]: from control import rss
In [2]: randomstatespace = rss(3,2,1)
In [3]: randomstatespace._repr_latex_()
Out[3]: '\\[\n\\left(\n\\begin{array}{rllrllrll|rll}\n-1.&\\hspace{-1em}79&\\hspace{-1em}\\phantom{\\cdot}&-0.&\\hspace{-1em}279&\\hspace{-1em}\\phantom{\\cdot}&-1.&\\hspace{-1em}77&\\hspace{-1em}\\phantom{\\cdot}&0.&\\hspace{-1em}223&\\hspace{-1em}\\phantom{\\cdot}\\\\\n-0.&\\hspace{-1em}652&\\hspace{-1em}\\phantom{\\cdot}&-1.&\\hspace{-1em}51&\\hspace{-1em}\\phantom{\\cdot}&-1.& …
```
> Get latex_to_png foreground color from stylesheet

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
qtconsole supports python 3.10 as shown in the setup.py:
https://github.com/jupyter/qtconsole/blob/cbffab2e0368fa42a6e10d0427c74aceaa1ee3d3/setup.py#L99
But the GitHub workflow doesn't cover them. This PR tries to solve that problem.
> Run tests with Python 3.10

- qtconsole/tests/test_jupyter_widget.py
@ccordoba12 I found the reasons why `test_other_output()` is failing under Qt6:
- The existing expected `toHtml()` output seems to be written for Qt <6.3. HTML output from Qt 6.3 also adds a style definition for `hr` (even though no `hr` tags are actually used). I have added the Qt 6.3 expected HTML and modified environment detection conditions so that the test can be run under versions both above and below 6.3. Let me know if the test should only expect to be run with Qt >=6.3 and the expected output for <6.3 should be dumped. Note that nothing about the actual output has been changed.
- `document` also sometimes gets garbage collected before the assertions are run, resulting in exceptions from Qt. I have pushed the variable assignments as late as possible to avoid this.
Let me know if …
> Fix test_other_output for Qt 6.3

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
Replace `_get_block_plain_text()` with `QTextBlock.text()`.
Fixes #531.
> Replace _get_block_plain_text() with QTextBlock.text() to fix segfault on Qt 6

- qtconsole/mainwindow.py
Replace `lambda` in syntax highlighting style `QAction` with partial objects in `init_view_menu()` for compatibility with PySide2 and Pyside6 (without breaking compatibility with PyQt5 and PyQt6).
Fixes #537.
> Fix missing argument error when switching syntax highlighting styles on PySide2 & PySide6

- scripts/jupyter-qtconsole
- setup.py
Remove the explicit "jupyter-qtconsole" script that is also covered
by an entry point.  Having both is redundant and causes "installer"
to fail on the resulting wheel.  Furthermore, installing explicit
scripts is deprecated in setuptools in favor of entry points.
Fixes #529
> Remove scripts that are duplicate to entry points in setup.py

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- qtconsole/console_widget.py
- That's not necessary on that platform
- It also fixes our test suite hanging for Mac on CIs.
> Don't call processEvents when showing input prompts on Mac

- qtconsole/qtconsoleapp.py
`LooseVersion` is deprecated. One way to avoid having to depend on 3rd party packages to check version numbers is to use Qt functions.
fixes #556
> Drop LooseVersion in favor of QVersionNumber

- .github/workflows/linux-tests.yml
This is because that version has a bug in QTextEdit (https://bugreports.qt.io/browse/QTBUG-107004), which should be solved in 6.4.1
> Avoid using PyQt 6.4.0 to run our tests

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- qtconsole/console_widget.py
Addresses spyder-ide/spyder#19888.
> Call processEvents when showing input prompts on Mac but not on tests

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/tests/test_00_console_widget.py
Resolves some PySide6 6.4.0 compatibility issues and follows enum usage conventions used elsewhere in the code base.
> Access cursor enums via base class

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- qtconsole/rich_jupyter_widget.py
- qtconsole/tests/test_jupyter_widget.py
- This fixes an error in Python 3.10+ when those values come as floats from Seaborn or Matplotlib.
- See https://github.com/spyder-ide/spyder/issues/20597 for more context.
> Cast images width and height to int when trying to insert them

- qtconsole/qtconsoleapp.py
- setup.py
This PR closes #567 
If using pyside6 backend, `QVersionNumber.fromString('5.15.2')` returns a `PySide6.QtCore.QVersionNumber` and as a result it is not subscriptable, so launching the console results in a `TypeError`.
Because the code refers to Qt5 versions, I've added a check that the backend isn't Qt6 prior to the version checking.
On my mac this console now works in pyside6 6.4.2, though there is a warning:
```
python3.10/site-packages/jupyter_client/threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.
Use zmq.Socket(shadow=other_socket)
or `ctx.socket(zmq.SUB, socket_class=zmq.Socket)`
to create a base zmq.Socket object,
no matter what other kind of socket your Context creates.
self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
```
I think that …
> Remove usage of `QVersionNumber` because it doesn't work as expected in PySide6

- qtconsole/client.py
- qtconsole/frontend_widget.py
- qtconsole/jupyter_widget.py
- qtconsole/manager.py
- qtconsole/tests/test_00_console_widget.py
Also, remove some unnecessary imports and variables.
> Fix kernel autorestart after it's killed for Jupyter-client 8+

- .gitignore
- qtconsole/inprocess.py
- qtconsole/tests/test_inprocess_kernel.py
In PR #574, a new function, `closed()` was added to the `QtZMQSocketChannel` class in order to check whether a channel was closed before flushing the stream. This must also be added to the `QtInProcessChannel` to ensure compatibility. Since in-process channels are never closed, this function should always return the value `False`.
This PR corrects the NeXpy issue [#378](https://github.com/nexpy/nexpy/issues/398) using the latest development version of qtconsole.
> Add missing `closed` method to `QtInProcessChannel`

- qtconsole/comms.py
- qtconsole/completion_html.py
- qtconsole/completion_plain.py
- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/rich_jupyter_widget.py
- qtconsole/util.py
- requirements/environment.yml
- setup.py
This vendors the code. 
~~There is still 1 place using ipython_genutils (`ensure_dir_exists`), but basically it is only called if you call `export_html(..., inline=False)`, which I can't find anywhere. So if you are willing to remove support for html export with non-inline html, then you can drop ipython_genutils dependency.~~
> Remove `ipython_genutils` as a dependency

- qtconsole/util.py
Also required by columnize, line 223, utils.py
Fixes #591.
> Fix some utility functions

- qtconsole/qtconsoleapp.py
Fix #594. It looks like `self.kernel_argv` would be empty anyway if the kernel was launched externally.
> Check for kernel manager in case we are dealing with an externally launched kernel

- docs/source/conf.py
The current format is deprecated since sphinx 6.2 and will be removed in the future.
> Use new format for instersphinx_mapping

- qtconsole/frontend_widget.py
This fixes an issue in PySide6 v6.6.2 where key sequence construction with the | operator is broken, and improves readability. 
Ideally this would be fixed in PySide6 or qtpy to retain original behavior, but since it also improves readability I think it makes sense to fix it here too.
Broken with PySide6 v6.6.2:
```py
from qtpy import QtCore
QtCore.Qt.AltModifier | QtCore.Qt.Key.Key_C
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 QtCore.Qt.AltModifier | QtCore.Qt.Key.Key_C
TypeError: unsupported operand type(s) for |: 'KeyboardModifier' and 'Key'
```
> Use string representation for QKeySequence construction

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- Our workflows are not running when PRs are merged to `main` because they are still targeting `master`.
- This should also fix updating our docs in Read the docs.
> Fix running workflows in the `main` branch

- qtconsole/tests/test_comms.py
Those tests started to fail failing frequently on Linux with Python 3.11
> Mark a couple of tests as flaky

- qtconsole/ansi_code_processor.py
- qtconsole/tests/test_ansi_code_processor.py
After:
Fixes #273 
Related to https://github.com/spyder-ide/spyder/issues/21225
> PR: Change ANSI color code 3 mapping from `brown` to `gold` and set bold format processing enabled by default

- qtconsole/tests/test_comms.py
Seems like the `test_comms` tests have been failing since when checking communications between kernel and frontend there is a possibility for a debugger warning message to appear (`Debugger warning: It seems that frozen modules are being used...`)
> Prevent debugger warning message from appearing while testing communications between kernel and frontend

- requirements/environment.yml
- setup.py
'pyzmq' is not used in sources, which was pulled in in 79b0b02f3
> Remove unnecessary `pyzmq` requirement

- qtconsole/console_widget.py
- qtconsole/frontend_widget.py
- qtconsole/tests/test_00_console_widget.py
Fix the handling of carriage return so it is not ignored at the end of a print line.
This allows for progress bars that rely on adding a carriage return at the end of the line such as:
```python
print("Progress 55%", end = "\r")
```
tl;dr
Preserve position of cursor so ANSI commands such as \r that modify position will preserve the position they specified over multiple calls. This is particularly relevant if time passes between print calls (~100 ms).
First of all, when you `print()` or call `sys.stdout.write()` in QtConsole, this ultimately causes the text to be passed to the frontend widget.
https://github.com/jupyter/qtconsole/blob/56e5a5ec5cfccf5afd098fe8bb5b2c558a1dc8f9/qtconsole/frontend_widget.py#L729
This will lead to the text by passed to the console widget, which will call the …
> Fix Carriage Return Handling in QtConsole

- qtconsole/_version.py
- qtconsole/ansi_code_processor.py
- qtconsole/mainwindow.py
- qtconsole/tests/test_jupyter_widget.py
Fixed traceback higlight, making use of the VerboseTB hack and adding a color homologation to expand the range of colors used by QtConsole
Before:
After:
**related issues**
https://github.com/spyder-ide/spyder/issues/4891
> Use selected syntax style for tracebacks and improve ANSI color codes support

- qtconsole/console_widget.py
Follow up for #607 as discussed at https://github.com/jupyter/qtconsole/pull/607#issuecomment-2276530999
> Missing code style suggestions from Carriage Return fix PR

- qtconsole/jupyter_widget.py
I don't think there is much reasons to lex Python 2 with such a recent QtConsole/IPython.
closes #588
> Remove Support for Python 2 Lexing

- qtconsole/ansi_code_processor.py
- qtconsole/console_widget.py
- qtconsole/tests/test_00_console_widget.py
- qtconsole/tests/test_ansi_code_processor.py
I made changes to the way the ANSI code \n is handled. Previously, whenever the \n code appeared, a new line was inserted unconditionally. After the change, a new line is inserted unless there is already a written line at the current position. In that case, instead of inserting a new line, the cursor moves one line down.
Preview with changes made:
Comparison of the result obtained with the changes made and in Ipython with QTDM
Preview with changes made:
Preview with IPython:
Fixes: #350 
Related with: https://github.com/spyder-ide/spyder-kernels/issues/494 https://github.com/spyder-ide/spyder/issues/6172
> Add logic to handle ANSI escape sequences to move cursor

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
See https://github.com/jupyter/qtconsole/actions/runs/12600493770/job/35119642403?pr=622#step:4:128 and https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
> Update setup-miniconda action version and use miniforge due to mambaforge sunsetting

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- qtconsole/jupyter_widget.py
- requirements/environment.yml
- setup.py
See https://github.com/ipython/ipython/issues/14520. The newly split package is already available now; I plan to leave the `IPython.lib.lexers` import working for a while, but I thought I'd update this while I'm thinking about it.
> IPython pygments lexers are moving to separate package

- .github/workflows/linux-tests.yml
- qtconsole/tests/test_inprocess_kernel.py
- setup.py
In ipykernel 7.0 start_kernel can be an async function.
> Test  async kernel manager

- qtconsole/tests/test_00_console_widget.py
- qtconsole/tests/test_comms.py
Use the `@pytest.mark.flaky` marker in place of the `@flaky.flaky` decorator, to modernize the code and improve compatibility with other plugins providing the feature such as `pytest-rerunfailures`.
> Replace `@flaky` decorator with pytest marker

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- setup.py
That version reached end-of-life last year.
> Drop support for Python 3.8

- docs/source/conf.py
This is possible since sphinx 1.8, and avoid the message:
>  "Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`"
at docs build time. See https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_suffix
> [Docs] Use `extension:filetype` mapping in Sphinx configuration
